name: Execute Unit Tests on Push

on: [push]

jobs:
  test:
    name: execute unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
    - name: npm install
      uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm test